language: python
  
matrix:
  include:
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"
    - os: osx
      language: generic

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install pytest; fi
install:
  - pip install .
script:
  - pytest
